export const LANGUAGES = {
	"arduino": "Arduino (C++)",
	"arm": "ARM Assembly",
	"bat": "Batch/DOS",
	"coffeescript": "CoffeeScript",
	"cmake": "CMake",
	"cs": "C#",
	"cpp": "C++",
	"c": "C",
	"css": "CSS",
	"go": "Go",
	"gradle": "Gradle",
	"groovy": "Groovy",
	"html": "HTML",
	"http": "HTTP",
	"java": "Java",
	"js": "JavaScript",
	"json": "JSON",
	"tex": "LaTeX",
	"less": "Less",
	"lisp": "Lisp",
	"lua": "Lua",
	"makefile": "Makefile",
	"markdown": "Markdown",
	"mathematica": "Mathematica",
	"matlab": "Matlab",
	"nim": "Nim",
	"objectivec": "Objective C",
	"ocaml": "OCaml",
	"glsl": "GLSL",
	"perl": "Perl",
	"php": "PHP",
	"ps": "PowerShell",
	"py": "Python",
	"r": "R",
	"ruby": "Ruby",
	"rust": "Rust",
	"sql": "SQL",
	"shell": "Shell",
	"swift": "Swift",
	"ts": "TypeScript",
	"x86asm": "x86 Assembly",
	"yml": "YAML",
};